debug: false
uuid: f0801c88-57cc-4e09-a460-7c2ad001cf20
token_id: lbh0pRidJ9nmEfow
token: Uv5aoUSH48TZ3uEs4lplUGUR03YFPoJuZehC7Fbi6FSEpQKbBvc38E0iMEMLqttM
api:
  host: 0.0.0.0
  port: 8443
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/tcwnodez.kelvinzmodz.my.id/fullchain.pem
    key: /etc/letsencrypt/live/tcwnodez.kelvinzmodz.my.id/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/elytra/volumes
  sftp:
    bind_port: 2022
  backups:
    rustic:
      binary_path: rustic
      repository_version: 2
      tree_pack_size_mb: 4
      data_pack_size_mb: 32
      local: { enabled: true, repository_path: /var/lib/pterodactyl/rustic-repos, use_cold_storage: false, hot_repository_path: '' }
      s3: { enabled: false, endpoint: '', region: us-east-1, bucket: '', use_cold_storage: false, hot_bucket: '', cold_storage_class: GLACIER, force_path_style: false, disable_ssl: false, ca_cert_path: '' }
allowed_mounts: []
remote: 'https://pyrodactyl-production-1d04.up.railway.app'
allowed_origins:
  - 'https://pyrodactyl-production-1d04.up.railway.app'
